<h2>添加后台用户</h2>
<div class="col-md-12" style="padding-left:0px;">
	<div class="panel panel-default">
				<div class="panel-heading">
					<span class="app-panel-title" >填写用户的基本资料</span>
				  	<a class="btn btn-sm btn-success app-panel-btn" href="/admin/adminuser/index/"> <i class="glyphicon glyphicon-chevron-right"></i> 返回用户列表</a>
				  	<div style="clear:both;"></div> 
				</div>

				  <div class="panel-body">
				  	<?php if(!empty($message)):?>
				  	<div class="alert alert-danger">
				  		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				  		<?php echo htmlspecialchars($message)?>
				  	</div>
				  	<?php endif;?>
				    <form action="/admin/adminuser/create" method="post" role="form" id="user-form">

				    	<?php if(!empty($info)):?>
				    		<input type="hidden" name="uid" value="<?php echo $info['uid']?>" />
				    	<?php endif;?>
						<div class="form-group">
							<label for="name">姓名</label>
					    	<input type="text" class="form-control" name="name" <?php if(!empty($info)):?>value="<?php echo $info['name']?>" <?php endif;?> id="name" placeholder="请输入姓名">
					    	<span class="help-block error"></span>
						</div>

						<div class="form-group">
							<label for="mobile">手机</label>
					    	<input type="text" class="form-control" name="mobile" <?php if(!empty($info)):?>value="<?php echo $info['mobile']?>" <?php endif;?> id="mobile" placeholder="请输入手机号">
					    	<span class="help-block error"></span>
						</div>

						<?php if(empty($info)):?>
						<div class="form-group">
							<label for="password">密码</label>
					    	<input type="password" class="form-control" name="password" <?php if(!empty($info)):?>value="<?php echo $info['password']?>" <?php endif;?> id="password" placeholder="请输入密码">
					    	<span class="help-block error"></span>
						</div>
						<?php endif;?>

						<button type="submit" class="btn btn-default" >提交</button>
					</form>
				</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$("#user-form").validate({
	rules: {
		name: { required:true },
		mobile: { required:true },
		password: {required:true}
	},
	messages: {
			name: {
				required: "姓名不能为空"
			},
			mobile: {
				required: "手机号不能为空"
			},
			password: {
				required:"密码不能为空"
			}
		},
		errorElement: "span",
		errorPlacement: function(error, element) {
				element.nextAll("span.error").replaceWith(error) ;
		}
});
</script>