<div class="row" style="margin-top:40px;">
	<div class="col-md-3">
		<?php include(dirname(dirname(__FILE__)).'/admin_left_menu.phtml');?>
	</div>
  	<div class="col-md-9">
  		 <div class="panel panel-default">
		  <div class="panel-heading">
        <span class="app-panel-title" >用户列表</span>
        <a class="btn btn-sm btn-success app-panel-btn" href="/admin/adminuser/create/"> <i class="glyphicon glyphicon-plus"></i>增加后台用户</a>
         <div style="clear:both;"></div>
		  </div>
		  
		  <div class="panel-body">
  	     	<table class="table table-bordered table-striped">
  	     		<tr><td>ID</td><td>姓名</td><td>手机号</td><td>更新日期</td><td>管理</td></tr>
  	     		<?php foreach ($show_list as $row){ ?>
  	     			<tr>
					  <td><?php echo $row['uid'];?></td>
					  <td><?php echo $row['name']?></td>
					  <td><?php echo $row['mobile']?></td>
					  <td><?php echo date('Y-m-d H:i',$row['updated_at']);?></td>
					  <td>
						  <a class="btn btn-info btn-xs" href="/admin/adminuser/role/?uid=<?php echo $row['uid']?>"><i class="glyphicon glyphicon-edit"> </i> 设置权限</a>
						  <a class="btn btn-success btn-xs" href="/admin/adminuser/create/?uid=<?php echo $row['uid']?>"><i class="glyphicon glyphicon-edit"> </i> 编辑</a>
						  <a class="btn btn-danger btn-xs" onclick="delAlert('/admin/adminuser/reset/?uid=<?php echo $row['uid']?>')"><i class="glyphicon glyphicon-edit"> </i> 重置密码</a>
					  </td>
					</tr>
  	     		<?php } ?>
  	 		</table>
        <?php $pager->render();?>
  	    </div>
  	    </div>
  	</div>
</div>