
<div class="login-panel">
    <div class="panel panel-default">
        <div class="panel-heading">重置密码</div>
        <div class="panel-body">
            <?php if(!empty($message)):?>
                <div class="alert alert-danger">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <?php echo htmlspecialchars($message)?>
                </div>
            <?php endif;?>
            <form action="/index/changepassword" method="post" role="form">
                <div class="form-group">
                    <label for="old_password">原密码</label>
                    <input type="password" class="form-control" name="old_password" placeholder="请输入原密码">
                </div>

                <div class="form-group">
                    <label for="exampleInputPassword">新密码</label>
                    <input type="password" class="form-control"  name="password"  placeholder="设置您的新密码">
                </div>
                <button type="submit" class="btn btn-default" >提交</button>
            </form>
        </div>
    </div>
</div>
</div>

