<div class="row" style="margin-top:40px;">
    <div class="col-md-3">
        <?php include(dirname(dirname(__FILE__)).'/admin_left_menu.phtml');?>
    </div>
    <div class="col-md-9">
        <style>
            .form-div{display:inline-block; min-width:400px;margin-bottom:15px;}
            .form-div label{width:100px;}
        </style>
        <form class="form-inline" role="form" action = "/admin/stat/index" method = "GET">
            <div class="form-div">
                <label>订单号：</label>
                <input type="text" name="trade_id" value="<?php if(!empty($params['trade_id'])){ echo $params['trade_id']; } ?>"/>
            </div>
            <div class="form-div" >
                <label>UID：</label>
                <input type="text"  name="uid" value="<?php if(!empty($params['uid'])){ echo $params['uid']; } ?>"/>
            </div>
            <br/>
            <div class="form-div" >
                <label>商品标题：</label>
                <input type="text"  name="item_title" value="<?php if(!empty($params['item_title'])){ echo $params['item_title']; } ?>"/>
            </div>
            <div class="form-div" >
                <label>订单状态：</label>
                <select name="tk_status">
                    <option value="0" <?php if(!isset($params['tk_status']) || $params['tk_status'] == '0' ){ echo "selected"; } ?>><?php echo '全部';?></option>
                    <?php foreach(TbOrderModel::ORDER_STATUS as $k=>$v){ ?>
                        <option value="<?php echo $k;?>" <?php if(isset($params['tk_status']) && $params['tk_status'] == $k ){ echo "selected"; } ?>><?php echo $v;?></option>
                    <?php } ?>
                </select>
            </div>
            <br>
            <button type="submit" class="btn btn-default">搜索</button>
            <br/><br/>
        </form>

        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="app-panel-title" >订单列表</span>
                <div style="clear:both;"></div>
            </div>
            <div class="panel-body">
                <table class="table table-bordered table-striped">
                    <tr><td>标题</td><td>UID</td><td>状态</td><td>支付</td><td>佣金</td><td>返利</td><td>下单时间</td><td>结算时间</td></tr>
                    <?php foreach ($show_list as $row){ ?>
                        <tr>
                            <td><a href="https://detail.tmall.com/item.htm?id=<?php echo $row['num_iid']?>" target="_blank"><?php echo $row['item_title'];?></a></td>
                            <td><a href="/admin/user/index?uid=<?php echo $row['uid']?>" target="_blank"><?php echo $row['uid'];?></a></td>
                            <td><?php echo TbOrderModel::ORDER_STATUS[$row['tk_status']];?></td>
                            <td><?php echo $row['alipay_total_price'];?></td>
                            <td><?php echo $row['pub_share_pre_fee'];?></td>
                            <td><?php echo $row['rebate'];?></td>
                            <td><?php echo $row['create_time'];?></td>
                            <td><?php echo $row['earning_time'];?></td>
                        </tr>
                    <?php } ?>
                </table>
                <?php $pager->render();?>
            </div>
        </div>
    </div>
</div>