<div class="row" style="margin-top:40px;">
    <div class="col-md-3">
        <?php include(dirname(dirname(__FILE__)).'/admin_left_menu.phtml');?>
    </div>
    <div class="col-md-9">
        <style>
            .form-div{display:inline-block; min-width:400px;margin-bottom:15px;}
            .form-div label{width:100px;}
        </style>
        <form class="form-inline" role="form" action = "/admin/shop/common" method = "GET">
            <div class="form-div" >
                <label>类型：</label>
                <select name="tk_status">
                    <?php foreach(CommonModel::TYPE as $v){ ?>
                        <option value="<?php echo $v;?>" <?php if(isset($params['type']) && $params['type'] == $v ){ echo "selected"; } ?>><?php echo $v;?></option>
                    <?php } ?>
                </select>
            </div>
            <br>
            <button type="submit" class="btn btn-default">搜索</button>
            <br/><br/>
        </form>

        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="app-panel-title" >配置列表</span>
                <a class="btn btn-sm btn-success app-panel-btn" href="/admin/shop/createcommon"> <i class="glyphicon glyphicon-plus"></i>增加配置</a>
                <div style="clear:both;"></div>
            </div>

            <div class="panel-body">
                <table class="table table-bordered table-striped">
                    <tr><td>key</td><td>value</td><td>创建日期</td><td>更新日期</td><td>管理</td></tr>
                    <?php foreach ($show_list as $row){ ?>
                        <tr>
                            <td><?php echo $row['key'];?></td>
                            <td><?php echo $row['value'];?></td>
                            <td><?php echo date('Y-m-d H:i',$row['created_at']);?></td>
                            <td><?php echo date('Y-m-d H:i',$row['updated_at']);?></td>
                            <td>
                                <a class="btn btn-success btn-xs" href="/admin/shop/createcommon?id=<?php echo $row['id']?>"><i class="glyphicon glyphicon-edit"> </i> 编辑</a>
                                <a class="btn btn-danger btn-xs" onclick="delAlert('/admin/shop/delcommon?id=<?php echo $row['id']?>')"> 删除</a>
                            </td>
                        </tr>
                    <?php } ?>
                </table>
            </div>
        </div>
    </div>
</div>