<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>领券教程</title>
    <link rel="icon" href="images/favicon.ico" type="img/x-ico" />
    <style type="text/css">
        body{
            background: #f4f4f4;
        }
        .main-container{
            display: flex;
            width: 90%;
            min-width: 400px;
            margin: 0 auto;
            flex-direction: column;
            align-items: center;
            padding-top: 60px;
            overflow: auto;
        }
        .title{
            display: flex;
            justify-content: center;
            margin-bottom: 20px;
        }
        .logo{
            width: 30px;
            height: 30px;
        }
        .logo img{
            width: 100%;
            height: 100%;
        }
        .t-title{
            color: #FC3C07;
            font-size: 22px;
            margin-left: 5px;
        }
        .item{
            margin-top: 36px;
        }
        .item:first-child{
            margin-top: 0;
        }
        .item-title{
            text-align: center;
            color: #FC3C07;
            font-size: 16px;
        }
        .item-desc{
            margin-top: 22px;
        }
        .item-desc-text{
            color: #666;
        }
        .item-desc-img{
            text-align: center
        }
        .item-desc-img img{
            margin-top: 8px;
            width: 85%;
            height: auto;
        }
        @media screen and (min-width: 1200px){
            .item{
                width: 500px;
            }
        }
        @media screen and (min-width: 970px) and (max-width: 1200px){
            .item{
                width: 500px;
            }
        }
        @media screen and (min-width: 768px) and (max-width: 970px){
            .item{
                width: 400px;
            }
        }
        @media screen and (min-width: 400px) and (max-width: 768px){
            .item{
                width: 400px;
            }
            .item-desc-text{
                font-size: 12px;
            }
        }
        @media screen and (max-width: 400px){
            .main-container{
                min-width: 320px;
            }
            .item-desc-text{
                font-size: 12px;
            }
            .item{
                width: 70%;
            }
        }
    </style>
</head>
<body>
<div class="main-container">
    <div class="title">
        <div class="logo"><img src="images/icon.png" alt=""></div>
        <div class="t-title">券购领券教程</div>
    </div>
    <div class="item">
        <div class="item-title">1.复制淘宝标题</div>
        <div class="item-desc">
            <div class="item-desc-text">
                打开手机淘宝App，选择您心仪的商品，打开商品详情页，长按复制商品标题或者链接；
            </div>
            <div class="item-desc-img">
                <img src="images/guide_1.png" alt="">
            </div>
        </div>
    </div>
    <div class="item">
        <div class="item-title">2.打开券购</div>
        <div class="item-desc">
            <div class="item-desc-text">
                打开券购App，自动为您搜索优惠券，并将您的心仪的商品自动展示在券购App；
            </div>
            <div class="item-desc-img">
                <img src="images/guide_2.png" alt="">
            </div>
        </div>
    </div>
    <div class="item">
        <div class="item-title">3.下单购买</div>
        <div class="item-desc">
            <div class="item-desc-text">
                点击领券购买/立即购买，跳转到手机淘宝App完成下单。
            </div>
            <div class="item-desc-img">
                <img src="images/guide_3.png" alt="">
                <img src="images/guide_4.png" alt="">
            </div>
        </div>
    </div>
</div>
</body>
</html>