<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>领券教程</title>
    <link rel="icon" href="/img/web/course/favicon.ico" type="img/x-ico" />
    <style type="text/css">
        body{
            background: #f4f4f4;
        }
        .main-container{
            display: flex;
            width: 90%;
            min-width: 700px;
            margin: 0 auto;
            flex-direction: column;
            align-items: center;
            padding-top: 60px;
            overflow: auto;
        }
        .title{
            display: flex;
            justify-content: center;
            margin-bottom: 20px;
        }
        .logo{
            width: 30px;
            height: 30px;
        }
        .logo img{
            width: 100%;
            height: 100%;
        }
        .t-title{
            color: #FC3C07;
            font-size: 22px;
            margin-left: 5px;
        }
        .item{
            margin-top: 36px;
        }
        .item:first-child{
            margin-top: 0;
        }
        .item-title{
            text-align: center;
            color: #FC3C07;
            font-size: 22px;
        }
        .item-desc{
            margin-top: 22px;
        }
        .item-desc-text{
            color: #666;
        }
        .item-desc-img{
            text-align: center
        }
        .item-desc-img img{
            margin-top: 8px;
            width: 85%;
            height: auto;
        }
        @media screen and (min-width: 1200px){
            .item{
                width: 800px;
            }
        }
        @media screen and (min-width: 970px) and (max-width: 1200px){
            .item{
                width: 800px;
            }
        }
        @media screen and (min-width: 768px) and (max-width: 970px){
            .item{
                width: 800px;
            }
        }
        @media screen and (min-width: 400px) and (max-width: 768px){
            .item{
                width: 680px;
            }
            .item-desc-text{
                font-size: 12px;
            }
        }
        @media screen and (max-width: 400px){
            .main-container{
                min-width: 360px;
            }
            .item-desc-text{
                font-size: 12px;
            }
            .item{
                width: 80%;
            }
        }
    </style>
</head>
<body>
<div class="main-container">
    <div class="title">
        <div class="logo"><img src="/img/web/course/icon.png" alt=""></div>
        <div class="t-title">券购怎么玩?</div>
    </div>
    <div class="item">
        <div class="item-desc">
            <div class="item-desc-text">
                券购是一款<b style="color: red">省</b>钱又可以<b style="color: red">赚</b>钱的购物App<br>
                <h2 style="color: red">省钱:</h2>
                <p style="text-align: center">省钱第一步  低价好货</p>
                &nbsp;&nbsp; &nbsp;&nbsp;在券购App里，你可以尽情浏览购买我们为您精心挑选的低价好货，看中的商品直接下单购买，物超所值。<br>
                <p style="text-align: center">省钱第二步  帮你找券</p>
                &nbsp;&nbsp; &nbsp;&nbsp;假如您已经在淘宝选好准备购买心仪的商品，我们还可以帮你以更优惠的方式买到。使用方式见下面领券教程。<br>

                <p style="text-align: center">省钱第三步  购物返利</p>
                &nbsp;&nbsp; &nbsp;&nbsp;在券购App里你购买的每一款商品都将获得一定比例的返利。<br>
                <br>
                <br>
                <h2 style="color: red">赚钱:</h2>
                <p style="text-align: center">赚钱第一步  分享</p>
                &nbsp;&nbsp; &nbsp;&nbsp;从券购App里分享商品给好友，好友下单购买，您一样可以获得返利。<br>
                动动手指即可返利翻倍，赶快分享起来吧!<br>
                <p style="text-align: center">赚钱第二步  邀请</p>
                &nbsp;&nbsp; &nbsp;&nbsp;近期我们会推出邀请好友功能，您邀请来的好友下单您将获得提成，邀请越多收益越多，日进斗金，敬请期待。<br>
                <h3>问答:</h3>
                <u>问:省钱第二步更优惠是指什么?</u><br>
                <span style="color: #111">答:帮你找到更大额的优惠券及"省钱第三步"带给您的购物返利。</span><br><br>
                <u>问:淘宝商品都有优惠吗?</u><br>
                <span style="color: #111">答:我们优先为你找到优惠券，如果商品没有优惠券不用着急，淘宝商品99%都有返利，"省钱第三步"购物拿返利更是一种优惠。</span><br><br>

                <u>问:返利何时可以提现?</u><br>
                <span style="color: #111">答:网上购物流程一般是下单后才会发货，快递到了签收后再确认收货，这个过程需要几天时间。<br>
                同样购物获得的返利发放到账也需要时间，我们需要核算您购买的订单，一般周期为您该笔订单在淘宝上确认收货后<b style="color: red">15天</b>可提现。<br><br>
                举例: 假如您5月2号在券购App下单购买了一款手机壳返利1元，5月5日您收到包裹，5月8日您在淘宝上点击了确认收货，那么您的这笔订单返利的1元可提现时间为5月23日(5月8日+15天)。<br>
                假如您收到包裹的5月5日当天就在淘宝上点击确认收货了，那您这笔订单的返利可提现时间也会提前到5月20日(5月5日+15天)。</span><br>
                <p style="color: hotpink;">温馨提示: 如果您希望更早的获得购物返利金，您需要收到包裹后尽快在淘宝里确认收货。</p><br>
                <u>问:返利如何提现?</u><br>
                <span style="color: #111">答:在券购App`我的`收益详情里有提现按钮，若找不到请先升级App至最新版本。按提示步骤操作即可提现，目前可以提现到支付宝，开放微信方式提现正在紧张开发中，敬请期待。</span><br><br>

            </div>
        </div>
    </div>
    
    <div class="item">
        <div class="item-title">领券教程</div>
    </div>
    <div class="item">
        <div class="item-desc">
            <div class="item-desc-text">
                1.打开手机淘宝App，选择您心仪的商品，打开商品详情页，长按复制商品标题或者链接；
            </div>
            <div class="item-desc-img">
                <img src="/img/web/course/guide_1.png" alt="">
            </div>
        </div>
    </div>
    <div class="item">
        <div class="item-desc">
            <div class="item-desc-text">
                2.打开券购App，自动为您搜索优惠券，并将您的心仪的商品自动展示在券购App；
            </div>
            <div class="item-desc-img">
                <img src="/img/web/course/guide_2.png" alt="">
            </div>
        </div>
    </div>
    <div class="item">
        <div class="item-desc">
            <div class="item-desc-text">
                3.点击领券购买/立即购买，跳转到手机淘宝App完成下单。
            </div>
            <div class="item-desc-img">
                <img src="/img/web/course/guide_3.png" alt="">
                <img src="/img/web/course/guide_4.png" alt="">
            </div>
        </div>
    </div>
</div>
</body>
</html>