


<!DOCTYPE HTML>
<html lang="en">
<head>


    <meta charset="utf-8" />



    <title>万能页官网-免费快速制作发布内容的好帮手</title>



    <meta id="viewport" name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="renderer" content="webkit">
    <meta content="万能页官网,内容发布工具，H5页面，微信朋友圈小卡片，手机网页制作,万能页是免费快速制作、碎片化内容发布的SAAS工具，可以帮助中小企业快速制作H5页面/微信朋友圈小卡片/手机网页制作。" name="keywords" />
    <meta content="" name="description" />
    <link rel="shortcut icon" type="image/ico" href="/statics/images/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="/statics/js/lib/nprogress/nprogress.css" rel="stylesheet" />
    <link rel="stylesheet" href="/statics/css/common.css?v=1.23.0" />
    <script>
        var IMG_CDN_URL = "http://img.wannengye.com/";
        var WEIXIN_IMG_CDN_URL = "http://wechat-share.wannengye.com/";
        var VIEW_PATH = "/pages/";

    </script>


    <link rel="stylesheet" href="/statics/css/index.css" />
    <style>
        .has-error .help-block,
        .has-error .control-label,
        .has-error .radio,
        .has-error .checkbox,
        .has-error .radio-inline,
        .has-error .checkbox-inline,
        .has-error.radio label,
        .has-error.checkbox label,
        .has-error.radio-inline label,
        .has-error.checkbox-inline label{
            color: #a94442;
        }
        .has-error .form-control {
            border-color: #a94442;
            -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);
            box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);
        }
        .has-error .form-control:focus {
            border-color: #843534;
            -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075), 0 0 6px #ce8483;
            box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075), 0 0 6px #ce8483;
        }
    </style>
</head>
<body>
<div class="ix_head">
    <div class="ix_headcont">
        <a class="ix_logo"></a>
        <div class="ix_nav">
            <a href="#video">视频教程</a> <a href="#case">推荐案例</a> <a
                href="javascript:;" class="login_register">注册</a> <a
                href="javascript:;" class="login">登录</a>
        </div>
        <div class="ix_muen">
            <i class="iconfont">&#xe60e;</i>
        </div>
        <div class="ix_user">
            <i class="iconfont">&#xe603;</i>
        </div>
    </div>
</div>
<div class="ix_head ix_head_1" style="display:none;">
    <div class="ix_headcont">
        <a class="ix_logo"></a>
        <div class="ix_nav">
            <a href="#video">视频教程</a> <a href="#case">推荐案例</a> <a
                href="javascript:;" class="login_register">注册</a> <a
                href="javascript:;" class="login">登录</a>
        </div>
        <div class="ix_muen">
            <span></span>
        </div>
        <div class="ix_user">
            <span></span>
        </div>
    </div>
</div>
<div class="ix_banner">
    <ul>
        <li>
            <h1>超简单的内容发布专家</h1>
            <h2>在线快速制作页面的好工具</h2>
            <p>想把什么放到网上吗？万能页帮您轻松实现！</p> <a href="javascript:;" class="ix_btn login">立即免费使用</a>
            <p class="b_fot">
                或者去看看<a href="#case">案例</a>
            </p>
        </li>
    </ul>
</div>
<div class="ix_toptag"></div>
<div class="ix_fun">
    <h2>抓住灵感的火花，将想法瞬间实现！随意组合编排内容，多种呈现方式！</h2>
    <div class="ix_funt">
        <ul>
            <li><span class="icont_1"></span>
                <h1>简单</h1>
                <p>
                    无代码可视化编辑！<br /> 会打字＋十分钟＝页面完成了！
                </p></li>
            <li><span class="icont_2"></span>
                <h1>移动适配</h1>
                <p>
                    一次制作同时完成，<br /> PC页面、移动页面和邮件模板！
                </p></li>
            <li><span class="icont_3"></span>
                <h1>数据统计</h1>
                <p>
                    访问数据按照页面单独统计，<br /> 为您精准营销提供有力的依据！
                </p></li>
        </ul>
    </div>
    <div class="ix_funb">
        <ul>
            <li><span class="iconb_1"></span>
                <h1>多种素材组件</h1>
                <p>文本、图文、图片、视频等多种组件随意组合，您也可以使用表单收集信息，更有按钮、简介、活动等等的功能组件供您选择！</p></li>
            <li><span class="iconb_2"></span>
                <h1>多种渠道分享</h1>
                <p>微博、微信、短信、邮件等多种渠道快速发布！或者您可以复制链接发送到您想发布的地方！同时提供打印通道，方面您的办公！</p></li>
            <li><span class="iconb_3"></span>
                <h1>多种排版方式</h1>
                <p>组件随意移动排列，切换排版样式，同样的内容不同编排，呈现给您不同的页面布局！</p></li>
        </ul>
    </div>
</div>
<div class="ix_bottomtag"></div>
<div class="ix_video" id="video">
    <div class="ix_vcont">
        <div class="ix_vcont_t">
            <video src="http://img.wannengye.com/intro1.mp4" controls="controls">您的浏览器不支持 video 标签。</video>
        </div>
        <a href="javascript:;" class="ix_btn login">立即免费使用</a>
    </div>
</div>
<div class="ix_case" id="case">
    <div class="ix_casecont">
        <div class="ix_pred"></div>
        <div class="ix_next"></div>
        <ul>
            <li class="first"><a
                    href="http://www.wannengye.com/view/index/54830c35745e8"><img
                        src="http://img.wannengye.com/caseimg.png" class="ix_pc" /><img
                        src="http://img.wannengye.com/caseimg_m.png" class="ix_mobile" /></a></li>
            <li><a
                    href="http://www.wannengye.com/view/index/540e691a8e44d"><img
                        src="http://img.wannengye.com/caseimg1.png" class="ix_pc" /><img
                        src="http://img.wannengye.com/caseimg_m1.png" class="ix_mobile" /></a></li>
            <li><a
                    href="http://www.wannengye.com/view/index/5497f02463cb4"><img
                        src="http://img.wannengye.com/caseimg2.png" class="ix_pc" /><img
                        src="http://img.wannengye.com/caseimg_m2.png" class="ix_mobile" /></a></li>
            <li><a
                    href="http://www.wannengye.com/view/index/54703749b33d5"><img
                        src="http://img.wannengye.com/caseimg3.png" class="ix_pc" /><img
                        src="http://img.wannengye.com/caseimg_m3.png" class="ix_mobile" /></a></li>
            <li><a
                    href="http://www.wannengye.com/view/index/541a85b05e8b5"><img
                        src="http://img.wannengye.com/caseimg4.png" class="ix_pc" /><img
                        src="http://img.wannengye.com/caseimg_m4.png" class="ix_mobile" /></a></li>
            <li class="last"><a
                    href="http://www.wannengye.com/view/index/5469bd40b0531"><img
                        src="http://img.wannengye.com/caseimg5.png" class="ix_pc" /><img
                        src="http://img.wannengye.com/caseimg_m5.png" class="ix_mobile" /></a></li>
        </ul>
    </div>
</div>
<div class="ix_about">
    <div class="ix_aboutcont">
        <h1>客服邮箱</h1>
        <h2>angel@wannengye.cn</h2>
        <div class="ix_lx">
            <a href="http://weibo.com/wannengye">官方微博</a> |
            <!-- <a href="javascript:;">加入万能页天使用户群(QQ群：226865360)</a> -->
            <a target="_blank" href="//shang.qq.com/wpa/qunwpa?idkey=bce4a05ff3e2c44d94987daa9bde1a2673a7e853dd165718d05349b32635cc9c"><img border="0" src="//pub.idqqimg.com/wpa/images/group.png" alt="万能页天使用户1群" title="万能页天使用户1群"></a>
            <!-- <a target="_blank" href="//shang.qq.com/wpa/qunwpa?idkey=7fc7073e6f128de66c7f72816c7d80f0cd6a4832bf348d8b7e8bae591a829ded"><img border="0" src="//pub.idqqimg.com/wpa/images/group.png" alt="万能页天使用户3群" title="万能页天使用户3群"></a> -->
            <!-- <a target="_blank" href="//shang.qq.com/wpa/qunwpa?idkey=54a2d967f9b8dd121d2c927e2898719de81cc6e9e20a60ab6e66a980138d8220"><img border="0" src="//pub.idqqimg.com/wpa/images/group.png" alt="万能页天使用户2群" title="万能页天使用户2群"></a> -->


        </div>
        <a href="javascript:;" class="ix_btn login">立即免费使用</a>
    </div>
</div>
<div class="ix_footer">
    <div class="ix_footercont">
        <h1>万能页</h1>
        <p>@2014 万能页 沪ICP备14033461号－1   <a href="/sp/protocol">用户协议</a> | <a href="/sp/contact_us">联系我们</a></p>
    </div>
</div>
<div class="login_common login_dl">
    <div class="login_commoncont">
        <div class="login_top">
            <strong>登录</strong><span>还没有账号？</span><a href="javascript:;"
                                                     class="login_register">注册</a>
            <div class="login_close">
                <i class="iconfont">&#xe60f;</i>
            </div>
        </div>
        <form id="formSignin" action="/signin" method="POST">
            <div class="h20"></div>
            <div class="login_input login_input_tips">
                <i class="iconfont">&#xe636;</i>
                <input type="text" class="form-control" name="loginName" placeholder="请输入您的邮箱" required value=""/>
            </div>
            <div class="h20"></div>
            <div class="login_input login_input_tips">
                <i class="iconfont">&#xe635;</i><input type="password" name="pwd" class="form-control" placeholder="请输入您的密码" required value=""/>
            </div>
            <div class="h10"></div>
            <p>
                <a href="javascript:;" class="login_forget">忘记密码？</a>
                <input name="autologin" type="checkbox" checked value="true"/>下次自动登录
            </p>
            <input class="hid_ip" type="hidden" name="ip" value="" />
            <input class="hid_city" type="hidden" name="city" value=""/>
            <div class="login_button btnSubmit" id="btn_login">登录</div>
            <div class="h20"></div>
            <div>
                <input type="hidden" name="CSRFToken" value="1aa15470-5b25-4671-bc8f-d471f46630e3" />
            </div></form>
    </div>
</div>
<div class="login_common login_zc" style="display:none;">
    <div class="login_commoncont">
        <div class="login_top">
            <strong>注册</strong><span>已有账号，请</span><a href="javascript:;"
                                                     class="login_in">登录</a>
            <div class="login_close">
                <i class="iconfont">&#xe60f;</i>
            </div>
        </div>
        <form id="formSignup" action="/signup" method="POST">
            <div class="h20"></div>
            <div class="login_input">
                <i class="iconfont">&#xe636;</i>
                <input type="text" class="form-control" id="signupEmail" name="email" placeholder="请输入您的邮箱" required/>
            </div>
            <div class="h20"></div>
            <div class="login_input">
                <i class="iconfont">&#xe635;</i>
                <input type="password" name="pwd" id="txtPwd" class="form-control" placeholder="请输入您的密码" required>
            </div>
            <div class="h20"></div>
            <div class="login_input">
                <i class="iconfont">&#xe635;</i>
                <input type="password" class="form-control" name="pwd2" placeholder="请再次输入您的密码" required>
            </div>
            <p>
                <input type="checkbox" name="agree" checked required />我已阅读并接受<a href="/sp/protocol" class="login_xy" target="_blank">《用户注册协议》</a>
            </p>
            <div class="h10"></div>
            <input class="hid_ip" type="hidden" name="ip" value=""/>
            <input class="hid_city" type="hidden" name="city"  value=""/>
            <input class="hid_ua" type="hidden" name="userAgent"  value=""/>
            <input class="hid_referer" type="hidden" name="referer"  value=""/>
            <input class="hid_employee" type="hidden" name="employee"  value=""/>
            <input class="hid_keyword" type="hidden" name="keyword"  value=""/>
            <input class="hid_source" type="hidden" name="source"  value=""/>
            <div class="login_button regist btnSubmit" id="btn_register">注册</div>
            <div class="h20"></div>
            <div>
                <input type="hidden" name="CSRFToken" value="1aa15470-5b25-4671-bc8f-d471f46630e3" />
            </div></form>
    </div>
</div>
<div class="login_common login_zh" style="display:none;">
    <div class="login_commoncont">
        <div class="login_top">
            <strong>找回密码</strong><a href="javascript:;" class="login_into">返回登录</a>
            <div class="login_close">
                <i class="iconfont">&#xe60f;</i>
            </div>
        </div>
        <form id="formForgotPwd" action="/;jsessionid=13BAB1429989ACFEEC7957D1760B3A8C" method="post">
            <div class="h20"></div>
            <p>
                <span class="red">请输入注册时的邮箱账号</span>
            </p>
            <div class="login_input">
                <i class="iconfont">&#xe636;</i><input type="text" name="email" placeholder="请输入注册时的邮箱账号" required/>
            </div>
            <div class="h20"></div>
            <div class="login_button getpass btnSubmit" id="btn_forgot_pwd">确定</div>
            <div class="h20"></div>
            <div>
                <input type="hidden" name="CSRFToken" value="1aa15470-5b25-4671-bc8f-d471f46630e3" />
            </div></form>
    </div>
</div>
<div class="ix_bg"></div>
<input type="hidden" id="hidResultType" value="" />
<input type="hidden" id="hidResultContent" value="" />
<input type="hidden" id="hidResultOption" value="" />






<script src="http://apps.bdimg.com/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="/statics/js/lib/nprogress/nprogress.js"></script>
<script src="/statics/js/lib/noty-2.3.8/jquery.noty.packaged.min.js"></script>
<script src="/statics/js/common.js?v=1.23.0"></script>
<script src="/statics/js/site.js?v=1.23.0"></script>



<script src="/statics/js/lib/jquery-validation-1.14.0/jquery.validate.min.js"></script>
<script src="/statics/js/lib/jquery-validation-1.14.0/jquery.validate.default.msg.js"></script>
<script src="/statics/js/website/index.js?v=1.23.0"></script>
<!-- 浏览器不支持 开始-->
<!-- 遮罩层 -->
<div class="windbg"></div>
<div id="div_old_browser" class="tips_windows" style="display:none;">
    <div class="tips_wintop">
        <h1>万能页提醒您</h1>
        <i class="iconfont share_close">&#xe60f;</i>
    </div>
    <div class="tips_wincont">
        <p>为了保证您能正常的使用万能页，建议您使用以下我们推荐的浏览器</p>
        <div class="tips_llq">
            <a href="http://img.wannengye.com/Chrome.exe" target="_blank"><img src="http://img.wannengye.com/icon_llq_1.png" width="80" /><p>下载Chrome浏览器</p></a>
            <a href="http://chrome.360.cn/" class="last" target="_blank"><img src="http://img.wannengye.com/icon_llq_2.png" width="80" /><p>下载360极速浏览器</p></a>
        </div>
    </div>
</div>
<script>
    $(function(){
        if($com.uaDetector.browser === "ie" && parseFloat($com.uaDetector.browserVersion) <= 11)
            $("#div_old_browser, .windbg").show();
        $("#div_old_browser .share_close").on("click",function(e){
            $("#div_old_browser, .windbg").hide();
        });
    });
</script>
<!-- 浏览器不支持 结束 -->
</body>
</html>
